language: android
jdk: oraclejdk8
android:
  components:
    - tools
    - platform-tools
    - build-tools-24.0.2
    - android-25
    - extra-android-m2repository

script:
    - ./gradlew check -PdisablePreDex --continue --stacktrace